name: Application release

permissions:
  id-token: write
  attestations: write
  contents: write

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update rust toolchain
        run: |
          rustup update
      - name: Build
        run: |
          cargo build --release
      - name: Generate Checksums
        run: |
          sha256sum target/release/certificate-issuer > sha256sum.txt
          md5sum target/release/certificate-issuer > md5sum.txt
      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: target/release/certificate-issuer
      - name: Publish release
        uses: softprops/action-gh-release@69320dbe05506a9a39fc8ae11030b214ec2d1f87
        with:
          name: ${{ github.ref_name }}
          files: |
            target/release/certificate-issuer
            LICENSE.md
            sha256sum.txt
            md5sum.txt
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true